### ISSUE TITLE
Is there a reference for Mechura's (2016) English lemmatization List used in the package? 

### ISSUE THREAD

**Issue by GabriellaS-K** [trinker/textstem#14]
Thanks for an awesome package. Is there a Is there a reference for Mechura's (2016) English lemmatization List used in the package? I will of course be referencing textstem in my paper, but would also like a ref for the list, and can't find on google. 

Many thanks!

**Comment by trinker** [comment]
https://github.com/trinker/lexicon/blob/master/R/hash_lemmas.R

**Comment by GabriellaS-K** [comment]
Thank you so much!
