### ISSUE TITLE
Default dictionary for lemmatize_strings replaces "also" with "conjurer"

### ISSUE THREAD

**Issue by mlinegar** [trinker/textstem#5]
For example, if I run:

`lemmatize_strings(c("this that also", "me too thanks", "also also"))`

I get:

`[1] "this that conjurer" "me too thank"       "conjurer conjurer" `

It's not a huge bug, but I was very confused about what was going on when I was running this on a larger corpus, and very curious about how it happened!

**Comment by trinker** [comment]
That is a big deal...thanks for the heads up...unsure of how it happened.

**Comment by mlinegar** [comment]
Not to worry! The package has been a huge help otherwise, so thanks for the great work!

**Comment by trinker** [comment]
I have fixed this in the lexicon package and will send to CRAN in a few weeks.  Thanks again for the spot.  The original error appears to be from the dictionary I scraped from.
